[package]
name = "corset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.3"
pest_derive = "2.0"
maplit = "1.0"
eyre = "0.6"
color-eyre = { version = "0.6", default-features = false }
clap = { bersion = "3.2", features = ["derive"] }
