[package]
name = "corset"
version = "1.1.0"
edition = "2021"
authors = [ "Franklin Delehelle <franklin.delehelle@consensys.net>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
clap-verbosity-flag = "1.0"
color-eyre = { version = "0.6", default-features = false }
colored = "2.0"
convert_case = "0.6"
eyre = "0.6"
indicatif = "0.17"
is-terminal = "0.3"
lazy_static = "1.4"
log = "0.4"
simplelog = { version = "0.12.0", features = ["paris"] }
maplit = "1.0"
names = { version = "0.12.0", default-features = false }
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
pairing_ce = "0.28"
pest = "2.3"
pest_derive = "2.0"
regex = "1.6"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
tabled = "0.9"

[profile.release]
debug = true
