[package]
name = "corset"
version = "1.1.0"
edition = "2021"
authors = [ "Franklin Delehelle <franklin.delehelle@consensys.net>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
color-eyre = { version = "0.6", default-features = false }
convert_case = "0.5"
eyre = "0.6"
lazy_static = "1.4"
maplit = "1.0"
num-bigint = "0.4"
num-traits = "0.2"
pest = "2.3"
pest_derive = "2.0"
regex = "1.6"
