[package]
name = "corset"
version = "1.1.0"
edition = "2021"
authors = [ "Franklin Delehelle <franklin.delehelle@consensys.net>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cached = { version = "0.40", default-features = false }
clap = { version = "4", features = ["derive", "wrap_help"] }
clap-verbosity-flag = "2"
colored = "2.0"
convert_case = "0.6"
flate2 = "1"
indicatif = { version = "0.17", optional = true }
is-terminal = "0.4"
itertools = "0.10"
lazy_static = "1.4"
log = "0.4"
maplit = "1.0"
names = { version = "0.12.0", default-features = false }
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
once_cell = "1.16"
pairing_ce = "0.28"
pest = { version = "2.4", optional = true }
pest_derive = { version = "2.4", optional = true }
postgres = { version = "0.19", optional = true }
rayon = "1.5"
ron = "0.8"
stderrlog = { version = "0.5", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }

[features]
default = [ "interactive" ]
postgres = [ "dep:postgres" ]
interactive = [ "dep:indicatif", "dep:pest", "dep:pest_derive" ]

[profile.release]
debug = true
