[package]
name = "corset"
version = "7.1.0"
edition = "2021"
authors = [ "Franklin Delehelle <franklin.delehelle@consensys.net>" ]
build = "build.rs"

[lib]
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "corset"
path = "src/main.rs"

[dependencies]
anyhow = "1"
buche = "0.7"
cached = { version = "0.43", default-features = false }
clap-verbosity-flag = "2"
clap = { version = "4", features = ["derive", "wrap_help", "cargo"] }
colored = "2.0"
convert_case = "0.6"
errno = "0.3.0"
flate2 = "1"
handlebars = { version = "4.3.6", default-features = false }
indicatif = { version = "0.17", optional = true }
is-terminal = "0.4"
itertools = "0.10"
lazy_static = "1.4"
libc = "0.2.139"
log = "0.4"
logging_timer = "1.1.0"
maplit = "1.0"
md5 = "0.7"
names = { version = "0.14.0", default-features = false }
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
once_cell = "1.17"
pairing_ce = "0.28"
pest_derive = { version = "2.4", optional = true }
pest = { version = "2.4", optional = true }
postgres = { version = "0.19", optional = true }
rayon = "1.5"
ron = "0.8"
serde_json = { version = "1", features = ["arbitrary_precision"] }
serde = { version = "1", features = ["derive"] }
sorbus = "0.9"
thiserror = "1.0.38"
buildstructor = "0.5.2"
either = { version = "1.8.1", features = ["serde"] }


[target.'cfg(all(target_arch = "x86_64", target_feature = "avx"))'.dependencies]
simd-json = "0.10"

[features]
default = ["interactive"]
interactive = ["dep:indicatif", "dep:pest", "dep:pest_derive"]
postgres = ["dep:postgres"]
conflater = []

[package.metadata.release]
tag-prefix = ""
publish = false
pre-release-hook = ["git-cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
allow-branch = ["master"]

# Always optimize dependencies
[profile.dev.package."*"]
opt-level = 3

[build-dependencies]
cbindgen = "0.24.3"
