name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
          rustflags: ""
    - name: Build
      run: cargo build -vv
      env:
        CORSET_TEST_LIMIT: 1000
    - name: Run tests
      run: cargo test -v
